package pro.sketchware.core.sync;

import java.util.ArrayList;
import java.util.List;

/**
 * A replacement (or suppression) of code that was <b>generated by Sketchware itself</b> and has no
 * owning block — framework/core sections such as {@code onCreate}, {@code setContent { ... }},
 * imports, Compose screens or the class declaration.
 * <p>
 * Before this mechanism existed, an edit to such a line was treated as "protected infrastructure"
 * and silently dropped by the synchronizer, which made the generated line come back after the next
 * sync/reload. Overrides are the persistent home for those edits: they are anchored by content and
 * re-applied on top of every fresh generated version of the file, both in the Java editor and during
 * builds/exports, so the user's latest code is never overwritten.
 * <p>
 * {@link #consumeLines} says how many consecutive generated lines the override replaces (1 for a
 * single line, the whole region for a block-region fallback). {@link #lines} is {@code empty} for a
 * deletion (the generated line is suppressed).
 */
public class LineOverride {

    /**
     * Stable id kept across saves so the engine can track an override.
     */
    public String id = "";

    /**
     * Trimmed text of the generated line the override starts at.
     */
    public String anchorText = "";

    /**
     * 0 based occurrence of {@link #anchorText} inside the generated file.
     */
    public int anchorOccurrence;

    /**
     * Trimmed text of the previous generated line. Used together with {@link #afterText} to
     * disambiguate identical lines (closing braces, repeated calls, …).
     */
    public String beforeText = "";

    /**
     * Trimmed text of the next generated line.
     */
    public String afterText = "";

    /**
     * Trimmed text of the enclosing block opener (method, listener, …). Fallback anchor when the
     * exact anchor line disappeared from a newer generated version.
     */
    public String contextText = "";

    /**
     * Number of generated lines starting at the anchor replaced by this override. {@code 1} for a
     * single framework line; the generated line count of a block region for region fallbacks.
     */
    public int consumeLines = 1;

    /**
     * The replacement lines, exactly as the user wrote them (indentation preserved). An empty list
     * means the generated lines are deleted and must not come back.
     */
    public List<String> lines = new ArrayList<>();

    /**
     * Set by the injector when the anchor could not be resolved. The override is then appended
     * (commented out) at the end instead of being deleted. This field is informational and reset
     * during every injection.
     */
    public boolean orphaned;

    public LineOverride() {
    }

    public LineOverride(String id) {
        this.id = id;
    }

    public boolean isDeletion() {
        return lines == null || lines.isEmpty();
    }

    public String text() {
        return lines == null ? "" : String.join("\n", lines);
    }

    public LineOverride copy() {
        LineOverride copy = new LineOverride(id);
        copy.anchorText = anchorText;
        copy.anchorOccurrence = anchorOccurrence;
        copy.beforeText = beforeText;
        copy.afterText = afterText;
        copy.contextText = contextText;
        copy.consumeLines = consumeLines;
        copy.lines = lines == null ? new ArrayList<>() : new ArrayList<>(lines);
        copy.orphaned = orphaned;
        return copy;
    }
}
