package pro.sketchware.core.sync;

import java.util.ArrayList;
import java.util.List;

/**
 * Result of comparing the Java source the user edited with the block based representation.
 * <p>
 * A plan is purely descriptive — nothing is written until {@link JavaSyncApplier} applies it, which
 * makes it possible to show the user what will happen and to ask for a decision when an automatic
 * resolution would be unsafe.
 * <p>
 * The plan is <i>loss free</i>: every user edit ends up in one of
 * <ul>
 *     <li>{@link #blockChanges} — an edit inside code generated by a block; the block is
 *     updated/removed so the block system reflects the edit,</li>
 *     <li>{@link #userCode} — brand-new code with no block behind it,</li>
 *     <li>{@link #lineOverrides} — edits (including deletions) of generated framework/core lines,
 *     kept as content-anchored overrides,</li>
 *     <li>{@link #wholeSource} — an emergency whole-file mode for edits that are too large to align
 *     line-by-line (never silently dropped).</li>
 * </ul>
 */
public class SyncPlan {

    public enum ChangeType {
        /**
         * A source-code block ({@code addSourceDirectly}) whose code was edited in the Java editor.
         */
        UPDATE_SOURCE_BLOCK,
        /**
         * A regular block whose generated code was edited. Java code cannot be turned back into an
         * arbitrary block, so the block is replaced by a source-code block holding the new code.
         */
        CONVERT_TO_SOURCE_BLOCK,
        /**
         * The generated code of a block was deleted in the Java editor → remove the block.
         */
        DELETE_BLOCK
    }

    public enum ConflictType {
        /**
         * Both the block and the Java code changed since the editor was opened.
         */
        BOTH_CHANGED,
        /**
         * The block disappeared (deleted in the logic editor) while its code was edited in Java.
         */
        BLOCK_REMOVED,
        /**
         * The block's code appears more than once in the generated file, so an edit cannot be
         * attributed unambiguously.
         */
        AMBIGUOUS_REGION
    }

    public static class BlockChange {
        public final ChangeType type;
        public final String regionId;
        public final String ownerKey;
        public final String blockId;
        public final String opCode;
        public final String oldText;
        public final String newText;
        /**
         * Display lines of {@link #newText}; carries the exact indentation the user used.
         */
        public final List<String> newTextLines;
        /**
         * {@code true} when this change is part of a conflict and is therefore kept on the Java
         * side (as an override) instead of touching blocks.
         */
        public boolean conflicted;
        /**
         * Safety net: an override that reproduces the same Java edit if applying the block change
         * fails. Never null for changes produced by a Java edit.
         */
        public LineOverride fallbackOverride;

        public BlockChange(ChangeType type, CodeRegion region, String oldText, String newText) {
            this(type, region, oldText, newText, null);
        }

        public BlockChange(ChangeType type, CodeRegion region, String oldText, String newText,
                           List<String> newTextLines) {
            this.type = type;
            this.regionId = region.id();
            this.ownerKey = region.ownerKey;
            this.blockId = region.blockId;
            this.opCode = region.opCode;
            this.oldText = oldText;
            this.newText = newText;
            this.newTextLines = newTextLines == null
                    ? splitLines(newText) : new ArrayList<>(newTextLines);
        }

        public String describe() {
            String where = ownerKey + " → block " + blockId;
            return switch (type) {
                case UPDATE_SOURCE_BLOCK -> "Update source code block (" + where + ")";
                case CONVERT_TO_SOURCE_BLOCK -> "Replace block '" + opCode + "' with a source code block (" + where + ")";
                case DELETE_BLOCK -> "Remove block '" + opCode + "' (" + where + ")";
            };
        }

        private static List<String> splitLines(String text) {
            List<String> lines = new ArrayList<>();
            if (text != null && !text.isEmpty()) {
                for (String line : text.replace("\r\n", "\n").split("\n", -1)) {
                    lines.add(line);
                }
            }
            return lines;
        }
    }

    public static class Conflict {
        public final ConflictType type;
        public final String regionId;
        public final String ownerKey;
        public final String blockId;
        public final String blockText;
        public final String javaText;

        public Conflict(ConflictType type, String regionId, String ownerKey, String blockId,
                        String blockText, String javaText) {
            this.type = type;
            this.regionId = regionId;
            this.ownerKey = ownerKey;
            this.blockId = blockId;
            this.blockText = blockText;
            this.javaText = javaText;
        }

        public String describe() {
            return switch (type) {
                case BOTH_CHANGED -> ownerKey + " → block " + blockId + " changed in blocks and in Java";
                case BLOCK_REMOVED -> ownerKey + " → block " + blockId + " no longer exists in the blocks";
                case AMBIGUOUS_REGION -> ownerKey + " → block " + blockId + " is generated more than once";
            };
        }
    }

    /**
     * {@code false} when the edited source could not be aligned with the generated one. The callers
     * must then fall back to {@link #wholeSource} instead of dropping anything.
     */
    public boolean reliable = true;
    /**
     * {@code true} when the block side changed while the Java editor was open (a freshly generated
     * region differs from the baseline, or a block was removed/added). The save-time verification
     * skips its whole-text recovery pass in that case, because the canonical source intentionally
     * differs from the stale editor text in exactly those block regions; a blind recovery would
     * revert the block-side changes with old Java text.
     */
    public boolean blockSideChanged;
    public final List<BlockChange> blockChanges = new ArrayList<>();
    /**
     * Complete new list of manually written code chunks (already re-anchored).
     */
    public final List<UserCodeChunk> userCode = new ArrayList<>();
    /**
     * Complete new list of frame overrides (edits to generated/core lines).
     */
    public final List<LineOverride> lineOverrides = new ArrayList<>();
    public final List<Conflict> conflicts = new ArrayList<>();
    /**
     * Number of generated framework lines the user changed or removed. Those edits are <b>kept</b>
     * as overrides and reported — they are no longer "rejected".
     */
    public int preservedGeneratedEdits;
    /**
     * Set when the file was too different to be diffed reliably: the whole edited source. The
     * applier stores it in manual whole-file mode.
     */
    public String wholeSource = "";
    /**
     * Hash of the baseline source for {@link #wholeSource}.
     */
    public String wholeSourceBaseHash = "";
    public final List<String> warnings = new ArrayList<>();
    /**
     * Region snapshots of the freshly generated source, stored after applying.
     */
    public java.util.Map<String, String> regionSnapshots = new java.util.HashMap<>();

    public boolean hasBlockChanges() {
        return !blockChanges.isEmpty();
    }

    /**
     * @return {@code true} for changes where a human decision used to be required. The save-time
     * synchronization always picks a non-lossy resolution automatically, so this is only used by
     * legacy/manual review flows.
     */
    public boolean requiresConfirmation() {
        if (!reliable) {
            return true;
        }
        if (!conflicts.isEmpty()) {
            return true;
        }
        for (BlockChange change : blockChanges) {
            if (change.type == ChangeType.CONVERT_TO_SOURCE_BLOCK) {
                return true;
            }
        }
        return false;
    }

    public boolean isEmpty() {
        return blockChanges.isEmpty() && conflicts.isEmpty()
                && userCode.isEmpty() && lineOverrides.isEmpty() && wholeSource.isEmpty();
    }
}
